package com.usbfile.usbstorage

import me.jahnen.libaums.core.driver.file.FileBlockDeviceDriver
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.RandomAccessFile
import kotlin.random.Random

/**
 * Host-side tests with disk images. Images are generated by scripts/make-test-images.sh
 * (mkfs.exfat / mkfs.ntfs / mkfs.ext4 / mkfs.fat); set USBFS_IMAGES to that directory.
 */
class UsbFsTest {
  private val dir: File? = System.getenv("USBFS_IMAGES")?.let(::File)?.takeIf { it.isDirectory }

  private fun image(name: String): File {
    assumeTrue("USBFS_IMAGES not set", dir != null)
    val f = File(dir, name)
    assumeTrue("missing $name", f.isFile)
    return f
  }

  private fun read(fs: RawFs, path: String): ByteArray =
    ByteArrayOutputStream().also { fs.readTo(path, it) }.toByteArray()

  private fun probe(f: File): RawFs {
    val r = VolumeProbe.probe(FileBlockDeviceDriver(f))
    assertNotNull("probe ${f.name}: detected=${r.detected} error=${r.error}", r.fs)
    return r.fs!!
  }

  private fun checkContent(fs: RawFs, full: Boolean) {
    assertEquals("hello from usb\n", String(read(fs, "/hello.txt")))
    if (!full) return
    assertEquals("nested 你好\n", String(read(fs, "/sub/nested.txt"), Charsets.UTF_8))
    val expected = File(dir, "content/sub/big.bin").readBytes()
    assertArrayEquals(expected, read(fs, "/sub/big.bin"))
    assertEquals(expected.size.toLong(), fs.stat("/sub/big.bin").size)
    val names = fs.list("/").map { it.name }
    assertTrue(names.toString(), names.contains("sub") && names.contains("hello.txt"))
  }

  @Test fun fat32ReadWriteLibaums() {
    val fs = probe(image("fat32_mbr.img"))
    assertEquals("FAT32", fs.typeName)
    assertFalse(fs.readOnly)
    assertEquals("MKFSFAT", fs.label)
    checkContent(fs, true)
    // write on a copy of a mkfs.fat volume, then check with fsck.fat outside the test
    val copy = File(dir, "fat32_written.img")
    image("fat32_mbr.img").copyTo(copy, overwrite = true)
    probe(copy).let { w ->
      w.mkdir("/new dir")
      w.writeFrom("/new dir/长文件名 file.txt", ByteArrayInputStream(Random.nextBytes(200_000)))
      w.delete("/sub/big.bin")
      w.close()
    }
    assertFatsEqual(copy)
  }

  @Test fun fat16ReadOnly() {
    val fs = probe(image("fat16_mbr.img"))
    assertTrue(fs.readOnly)
    assertTrue(fs.capacity() > 60L shl 20)
    checkContent(fs, true)
  }

  @Test fun ext4ReadOnly() {
    val fs = probe(image("ext4_mbr.img"))
    assertTrue(fs.typeName, fs.typeName.startsWith("ext"))
    assertTrue(fs.readOnly)
    assertEquals("EXT4VOL", fs.label)
    checkContent(fs, true)
    try { fs.mkdir("/x"); fail("ext must be read-only") } catch (e: Exception) { }
  }

  @Test fun ntfsReadOnly() {
    val fs = probe(image("ntfs_mbr.img"))
    assertEquals("NTFS", fs.typeName)
    assertTrue(fs.readOnly)
    checkContent(fs, false)
    assertFalse(fs.list("/").any { it.name.startsWith("$") })
  }

  @Test fun exfatPartitioned() {
    val fs = probe(image("exfat_mbr.img"))
    assertEquals("exFAT", fs.typeName)
    assertTrue(fs.readOnly)
    assertEquals("EXFATVOL", fs.label)
    fs.list("/")
    assertTrue(fs.capacity() > 100L shl 20)
    assertTrue(fs.free() in (fs.capacity() - (4L shl 20))..fs.capacity())
  }

  @Test fun exfatSuperfloppy() {
    val fs = probe(image("exfat_raw.img"))
    assertEquals("exFAT", fs.typeName)
    assertEquals("EXRAW", fs.label)
  }

  @Test fun formatFat32ThenReadWrite() {
    assumeTrue(dir != null)
    val img = File(dir, "formatted.img")
    RandomAccessFile(img, "rw").use { it.setLength(0); it.setLength(256L shl 20) }
    // garbage in the old partition table / boot area must not survive
    RandomAccessFile(img, "rw").use { it.write(Random.nextBytes(64 * 1024)) }
    Fat32Formatter.format(FileBlockDeviceDriver(img), "my usb")

    val payload = Random.nextBytes(1_234_567)
    probe(img).let { fs ->
      assertEquals("FAT32", fs.typeName)
      assertEquals("MY USB", fs.label)
      assertTrue(fs.list("/").isEmpty())
      assertTrue(fs.free() > 200L shl 20)
      fs.writeFrom("/a.txt", ByteArrayInputStream("abc".toByteArray()))
      fs.mkdir("/dir")
      fs.writeFrom("/dir/b.bin", ByteArrayInputStream(payload))
      fs.rename("/a.txt", "renamed.txt")
      fs.close()
    }
    probe(img).let { fs ->
      assertEquals("abc", String(read(fs, "/renamed.txt")))
      assertArrayEquals(payload, read(fs, "/dir/b.bin"))
      fs.delete("/renamed.txt")
      assertEquals(listOf("dir"), fs.list("/").map { it.name })
      fs.close()
    }
    assertFatsEqual(img)
  }

  /** Both FAT copies must be identical after libaums writes (see FatMirrorDevice). */
  private fun assertFatsEqual(img: File) {
    RandomAccessFile(img, "r").use { f ->
      val boot = ByteArray(512)
      val start = 1L shl 20
      f.seek(start); f.readFully(boot)
      val b = java.nio.ByteBuffer.wrap(boot).order(java.nio.ByteOrder.LITTLE_ENDIAN)
      val reserved = b.getShort(14).toLong()
      val fatBytes = b.getInt(36).toLong() * 512
      val a = ByteArray(fatBytes.toInt()); val c = ByteArray(fatBytes.toInt())
      f.seek(start + reserved * 512); f.readFully(a)
      f.readFully(c)
      assertArrayEquals(a, c)
    }
  }

  /** Leaves formatted_fresh.img untouched after formatting, for fsck.fat / mtools checks. */
  @Test fun formatOnly() {
    assumeTrue(dir != null)
    val img = File(dir, "formatted_fresh.img")
    RandomAccessFile(img, "rw").use { it.setLength(0); it.setLength(2L shl 30) }
    Fat32Formatter.format(FileBlockDeviceDriver(img), "FRESH")
  }

  @Test fun formatLargeSparse() {
    assumeTrue(dir != null)
    val img = File(dir, "formatted_40g.img")
    RandomAccessFile(img, "rw").use { it.setLength(0); it.setLength(40L shl 30) }
    Fat32Formatter.format(FileBlockDeviceDriver(img), "BIG")
    val fs = probe(img)
    assertEquals("FAT32", fs.typeName)
    assertTrue(fs.capacity() > 39L shl 30)
    fs.writeFrom("/x.txt", ByteArrayInputStream("x".toByteArray()))
    fs.close()
  }

  @Test fun planLimits() {
    val small = Fat32Formatter.plan(512, (64L shl 20) / 512)
    assertEquals(1, small.spc)
    assertTrue(small.clusters >= 65525)
    assertEquals(64, Fat32Formatter.plan(512, (64L shl 30) / 512).spc)
    assertEquals(8, Fat32Formatter.plan(512, (4L shl 30) / 512).spc)
    try { Fat32Formatter.plan(512, (16L shl 20) / 512); fail("too small") } catch (e: UserError) { }
    try { Fat32Formatter.plan(512, (2L shl 40) / 512); fail("too big") } catch (e: UserError) { }
    try { Fat32Formatter.normalizeLabel("bad/label"); fail() } catch (e: UserError) { }
    assertEquals("ABC", Fat32Formatter.normalizeLabel(" abc "))
  }
}
